version: '2.1'
services:
    postgres:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: devtechieinteractive/apache-airflow:1.10.1
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - /Users/rohithreddykota/Personal/Projects/airflow/apache-airflow/src/dags:/usr/local/airflow/dags
            - /Users/rohithreddykota/Personal/Projects/airflow/apache-airflow/Movie:/usr/local/airflow/Movie
            - /Users/rohithreddykota/Personal/Projects/airflow/apache-airflow/src/utils:/usr/local/airflow/utils
            # Uncomment to include custom plugins
#            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8088:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
